
[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  name = "gopkg.in/launchdarkly/go-sdk-common.v2"
  source = "github.com/launchdarkly/go-sdk-common-private"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "v1"
  name = "github.com/launchdarkly/go-test-helpers"
