version: 2.1

orbs:
  win: circleci/windows@1.0.0

workflows:
  workflow:
    jobs:
      - go-test:
          name: Go 1.15
          docker-image: circleci/golang:1.15
          run-lint: true
          with-coverage: true
      - go-test:
          name: Go 1.14
          docker-image: circleci/golang:1.14
          run-lint: true
      - go-test-windows:
          name: Windows
      - benchmarks

jobs:
  go-test:
    parameters:
      docker-image:
        type: string
      run-lint:
        type: boolean
        default: false
      with-coverage:
        type: boolean
        default: false
  
    docker:
      - image: <<parameters.docker-image>>
        environment:
          CIRCLE_TEST_REPORTS: /tmp/circle-reports
          CIRCLE_ARTIFACTS: /tmp/circle-artifacts

    steps:
      - checkout

      - run:
          name: install go-junit-report
          command: go get -u github.com/jstemmer/go-junit-report

      - run: go build ./...

      - when:
          condition: <<parameters.run-lint>>
          steps:
            - run: make lint
      
      - run:
          name: Run tests
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS
            mkdir -p $CIRCLE_ARTIFACTS
            trap "go-junit-report < $CIRCLE_ARTIFACTS/report.txt > $CIRCLE_TEST_REPORTS/junit.xml" EXIT
            make test | tee $CIRCLE_ARTIFACTS/report.txt

      - when:
          condition: <<parameters.with-coverage>>
          steps:
            - run:
                name: Verify test coverage
                command: make test-coverage
            - run:
                name: Store coverage results
                command: cp build/coverage* /tmp/circle-artifacts
                when: always
          
      - store_test_results:
          path: /tmp/circle-reports

      - store_artifacts:
          path: /tmp/circle-artifacts

  go-test-windows:
    executor:
      name: win/vs2019
      shell: powershell.exe

    environment:
      GOPATH: C:\Users\VssAdministrator\go

    steps:
      - checkout
      - run: go version
      - run:
          name: build and test
          command: |
            go test -race ./...

  benchmarks:
    docker:
      - image: circleci/golang:1.15
        environment:
          CIRCLE_ARTIFACTS: /tmp/circle-artifacts

    steps:
      - checkout
      - run: go build ./...      
      - run:
          name: Run benchmarks
          command: |
            mkdir -p $CIRCLE_ARTIFACTS
            make benchmarks | tee $CIRCLE_ARTIFACTS/benchmarks.txt

      - store_artifacts:
          path: /tmp/circle-artifacts
