version: 2

repo:
  public: go-sdk-events
  private: go-sdk-events-private

jobs:
  - docker:
      image: golang:1.14-buster
    template:
      name: go
    env:
      LD_RELEASE_GO_IMPORT_PATH: gopkg.in/launchdarkly/go-sdk-events.v1

branches:
  - name: v1

publications:
  - url: https://godoc.org/gopkg.in/launchdarkly/go-sdk-events.v1
    description: documentation
