version: 2

repo:
  public: go-sdk-events
  private: go-sdk-events-private

jobs:
  - docker:
      image: golang:1.18-buster
    template:
      name: go

branches:
  - name: v3
    description: 3.x - for Go SDK 7+
  - name: v2
    description: 2.x - for Go SDK 6+
  - name: v1
    description: 1.x - for Go SDK 5+

publications:
  - url: https://godoc.org/github.com/launchdarkly/go-sdk-events/v2
    description: documentation
