repo:
  public: go-sdk-events
  private: go-sdk-events-private

releasableBranches:
  - name: v1

template:
  name: go

publications:
  - url: https://godoc.org/github.com/launchdarkly/go-sdk-events
    description: documentation
